Added additional functionality to help with backspacing characters.
Error: If an operater was pressed and then the backspace button was pressed, then change the operator again. It would override the numbers before the operator.

EX: '23 + ' -> backspace button -> '23 +' -> change operater -> '2 - '
Now works properly by using an added function to check the last character and if that character is either an operator or a ' ' (space char) then it will backspace only once depending on the type of character. Up to 3 backspaces max ( because ' + ' is 3 chars and ' -' is 2 chars so we only want to override them if they are in a specific order)